# Generated by Django 3.2.6 on 2021-08-10 07:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bge',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
