# Generated by Django 3.2.6 on 2021-08-10 10:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bge', '0002_alter_bge_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bge',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
